- _redirects/sungk44.html
Hello, I've added my beautiful link!
> added sungk44 beautiful link to the rediects folder

- _redirects/ljw.html
I wanted to create a super short url to my github page.
> Created ljw.html

- _redirects/wsegura.html
- readme.md
> upload contribution

- _redirects/maryC.html
> Created redirect

- _redirects/ananthavijay.html
- readme.md
fixes https://github.com/gitdotio/gitdotio.github.io/issues/3
> Added my cool link 

- _redirects/gcoria.html
- readme.md
> coolLink added :)

- _redirects/jacobproffer.html
- readme.md
Added jacobproffer.html and updated README.md.
> Contribution

- _redirects/mswebgirl.html
- readme.md
> Hacktoberfest

- _redirects/izamglima.html
- readme.md
> Added my link to the project

- _redirects/iiqrah.html
Tried this site as a part of Hacktoberfest
> Added HackNotts Project URL

- _redirects/dr-wolf.html
- readme.md
> from Dr-Wolf-ML

- _redirects/alinmigea.html
Create the HTML file for mapping the GitHub link with your permalink.
> Create HTML file with permalink and destination

- _redirects/drumMachine.html
- readme.md
I went and added `drumMachine.html` to the repo and added myself @PeterCr to to the contributors 
list in the `readme.md` file :smile: :+1: 
Thanks so much, and Happy Hacktoberfest :maple_leaf: :ghost:
> Added new Link and myself to the readme.md file

- readme.md
I just added my name to the list.
> Update Readme with my name

- _redirects/sunpech.html
- readme.md
> Added redirect html file.

- _redirects/PrateekPardeshi.html
- prateek.html
Update in PrateekPardeshi.html
> Update in PrateekPardeshi.html

- _redirects/bustacodes.html
> adding bustacodes redirect

- readme.md
> Added myself

- _redirects/swayam.html
> added link

- readme.md
Update readme.md : Added my name in the list
> Update readme.md : Added my name in the list

- forumexercise.html
> forum in html

- _redirects/moisesjsalmeida.html
- readme.md
Please accept this pull request.
> added moisesjsalmeida.html
